"""Added initial table

Revision ID: 9311efdaedb5
Revises: 
Create Date: 2022-08-03 01:34:27.511064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9311efdaedb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('shop_product_code', sa.String(length=256), nullable=True),
    sa.Column('order_time_start', sa.DateTime(), nullable=True),
    sa.Column('order_time_end', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('original_website', sa.String(length=256), nullable=True),
    sa.Column('img_url', sa.String(length=256), nullable=True),
    sa.Column('order_status', sa.String(length=256), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_shop_product_code'), 'products', ['shop_product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_shop_product_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
